apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadbalancer
  labels:
    app: loadbalancer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadbalancer
  template:
    metadata:
      labels:
        app: loadbalancer
    spec:
      containers:
      - name: loadbalancer
        image: searchengine-loadbalancer:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Kubernetes"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
spec:
  selector:
    app: loadbalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30280  # External access
  type: NodePort
